Add fixups because copy-paste was outdated

diff --git a/.github/workflows/repackage.yml b/.github/workflows/repackage.yml
--- a/.github/workflows/repackage.yml
+++ b/.github/workflows/repackage.yml
@@ -14,37 +14,45 @@ jobs:
           repository: stellar/js-stellar-base
           fetch-depth: 0
           persist-credentials: false
-          path: sdk
 
       - name: Checkout Bower
         uses: actions/checkout@v3
         with:
           repository: stellar/bower-js-stellar-base
-          path: sdk/bower
+          fetch-depth: 0
+          ref: master
+          path: bower
 
-      - name: Check for updated SDK
-        # if this check fails then the job doesn't need to proceed
+      # if this check fails then the job doesn't need to proceed
+      - name: Check for updated base package
+        shell: bash
         run: |
-          cd sdk/
           TAG=`git describe --tags`
           cd bower/
-          [ "`git log -1 --pretty=%B`" == "$TAG" ] && exit 1
+          OLDTAG=`git describe --abbrev=0 --tags`
+          if [ "$OLDTAG" == "$TAG" ]; then
+            echo "No new JavaScript Base version was found, skipping run."
+            exit 1
+          else
+            echo "::group::New JavaScript Base version found:"
+            echo "Previous version: $OLDTAG"
+            echo "New version: $TAG"
+            echo "::endgroup::"
+          fi
 
       - name: Install Node (14.x)
-        uses: actions/setup-node@v2
+        uses: actions/setup-node@v3
         with:
           node-version: '14.x'
 
       - name: Install and build package
         run: |
-          cd sdk
           yarn install
-          yarn prepare
+          yarn
           cp dist/* bower/
 
       - name: Publish package
         run: |
-          cd sdk/
           TAG=`git describe --tags`
           cd bower/
           git config user.name github-actions
